package vm

// Code generated by go generate; DO NOT EDIT.
const (
	opAdd        = 1
	opAddp       = 2
	opAtan       = 3
	opAux        = 4
	opClip       = 5
	opCompressor = 6
	opCrush      = 7
	opDbgain     = 8
	opDelay      = 9
	opDistort    = 10
	opEnvelope   = 11
	opEnvelopexp = 12
	opFilter     = 13
	opGain       = 14
	opHold       = 15
	opIllogic    = 16
	opIn         = 17
	opInvgain    = 18
	opLoadnote   = 19
	opLoadval    = 20
	opMul        = 21
	opMulp       = 22
	opNoise      = 23
	opOscillator = 24
	opOut        = 25
	opOutaux     = 26
	opPan        = 27
	opPop        = 28
	opPush       = 29
	opReceive    = 30
	opSend       = 31
	opSignlogic  = 32
	opSpeed      = 33
	opSync       = 34
	opXch        = 35
)

var transformCounts = [...]int{0, 0, 0, 1, 0, 5, 1, 1, 4, 1, 5, 7, 2, 1, 1, 5, 0, 1, 0, 1, 0, 0, 2, 6, 1, 2, 1, 0, 0, 0, 1, 5, 0, 0, 0}
