package vm

// Code generated by go generate; DO NOT EDIT.
const (
	opAdd        = 1
	opAddp       = 2
	opAtan       = 3
	opAux        = 4
	opBelleq     = 5
	opBytelogic  = 6
	opClip       = 7
	opCompressor = 8
	opCrush      = 9
	opDbgain     = 10
	opDelay      = 11
	opDistort    = 12
	opEnvelope   = 13
	opEnvelopexp = 14
	opFilter     = 15
	opFloatlogic = 16
	opGain       = 17
	opHold       = 18
	opIn         = 19
	opInvgain    = 20
	opLoadnote   = 21
	opLoadval    = 22
	opMul        = 23
	opMulp       = 24
	opNoise      = 25
	opOscillator = 26
	opOut        = 27
	opOutaux     = 28
	opPan        = 29
	opPop        = 30
	opPush       = 31
	opReceive    = 32
	opReeeverb   = 33
	opSend       = 34
	opSignlogic  = 35
	opSpeed      = 36
	opSync       = 37
	opXch        = 38
)

var transformCounts = [...]int{0, 0, 0, 1, 3, 5, 0, 5, 1, 1, 4, 1, 5, 6, 2, 5, 1, 1, 0, 1, 0, 1, 0, 0, 2, 6, 1, 2, 1, 0, 0, 0, 2, 1, 5, 0, 0, 0}
