package vm

// Code generated by go generate; DO NOT EDIT.
const (
	opAdd        = 1
	opAddp       = 2
	opAtan       = 3
	opAux        = 4
	opBelleq     = 5
	opBytelogic  = 6
	opClip       = 7
	opCompressor = 8
	opCrush      = 9
	opDbgain     = 10
	opDelay      = 11
	opDistort    = 12
	opEnvelope   = 13
	opEnvelopexp = 14
	opFeeelall   = 15
	opFeeelter   = 16
	opFilter     = 17
	opFloatlogic = 18
	opGain       = 19
	opGate       = 20
	opHold       = 21
	opIn         = 22
	opInvgain    = 23
	opLoadnote   = 24
	opLoadval    = 25
	opMul        = 26
	opMulp       = 27
	opNoise      = 28
	opOscillator = 29
	opOut        = 30
	opOutaux     = 31
	opPan        = 32
	opPop        = 33
	opPush       = 34
	opReceive    = 35
	opSend       = 36
	opSignlogic  = 37
	opSpeed      = 38
	opSync       = 39
	opXch        = 40
)

var transformCounts = [...]int{0, 0, 0, 1, 3, 5, 0, 5, 1, 1, 4, 1, 5, 7, 5, 3, 2, 5, 1, 4, 1, 0, 1, 0, 1, 0, 0, 2, 6, 1, 2, 1, 0, 0, 0, 1, 5, 0, 0, 0}
